/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package playground

import org.junit.runner.RunWith
import org.scalatest.funsuite.AnyFunSuite
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends AnyFunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()

    assert(library.someLibraryMethod())
  }
}
